name: ä¸‹è½½è½¯ä»¶å¹¶å‘å¸ƒæ–‡ä»¶

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  schedule:
   - cron: 0 17 * * 5
env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 
  UPLOAD_2: true 
  UPLOAD_3: true 
  UPLOAD_4: true
  UPLOAD_5: true 
  UPLOAD_6: true 
  UPLOAD_7: true
  UPLOAD_8: true
  UPLOAD_9: true 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: è®¾ç½®ç¯å¢ƒ Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: å®‰è£…ä¾èµ–
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: ä¸‹è½½æ–‡ä»¶
        run: |
          python ./download.py
          # wget -q --show-progress  "$url" -P ruanjian 

      - name: è®¾ç½®å˜é‡
        id: compile
        run: |
          echo "bgcode=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          mv ruanjian.zip ./path
          FILE_NAMES=($(ls ./path))
          count=1
          for filename in "${FILE_NAMES[@]}"; do
            echo "FILE_NAME${count}=${filename}" >> $GITHUB_ENV
            ((count++))
          done
          echo "release_tag=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
    
      - name: ä¸Šä¼ æ–‡ä»¶1
        if: env.UPLOAD_1 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME1 }}
            path: ./path/${{ env.FILE_NAME1 }}
      - name: ä¸Šä¼ æ–‡ä»¶2
        if: env.UPLOAD_2 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME2 }}
            path: ./path/${{ env.FILE_NAME2 }}
      - name: ä¸Šä¼ æ–‡ä»¶3
        if: env.UPLOAD_3 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME3 }}
            path: ./path/${{ env.FILE_NAME3 }}
      - name: ä¸Šä¼ æ–‡ä»¶4
        if: env.UPLOAD_4 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME4 }}
            path: ./path/${{ env.FILE_NAME4 }}
      - name: ä¸Šä¼ æ–‡ä»¶5
        if: env.UPLOAD_5 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME5 }}
            path: ./path/${{ env.FILE_NAME5 }}
      - name: ä¸Šä¼ æ–‡ä»¶6
        if: env.UPLOAD_6 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME6 }}
            path: ./path/${{ env.FILE_NAME6 }}
      - name: ä¸Šä¼ æ–‡ä»¶7
        if: env.UPLOAD_7 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME7 }}
            path: ./path/${{ env.FILE_NAME7 }}
      - name: ä¸Šä¼ æ–‡ä»¶8
        if: env.UPLOAD_8 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAME8 }}
            path: ./path/${{ env.FILE_NAME8 }}
      - name: ä¸Šä¼ æ–‡ä»¶9
        if: env.UPLOAD_9 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
          name: bgcode_${{ env.FILE_NAME9 }}
          path: ./path/${{ env.FILE_NAME9 }}
      - name: Upload firmware to cowtransfer
        id: cowtransfer
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer cow --block 2621440 -s -p 64 --no-progress  ./path/${{ env.FILE_NAME9 }} 2>&1 | tee cowtransfer.log  
          echo "$(cat cowtransfer.log)"
          echo "cowtransfer=$(cat cowtransfer.log | grep https | cut -f3 -d" ")" >> $GITHUB_ENV

      - name: åˆ›å»ºé“¾æ¥
        id: ss
        run: |
            link_url=(
                "https://gh.h233.eu.org/https://github.com"
                "https://gh.ddlc.top/https://github.com"
                "https://dl.ghpig.top/https://github.com"
                "https://slink.ltd/https://github.com"
                "https://git.xfj0.cn/https://github.com"
                "https://gh.con.sh/https://github.com"
                "https://ghps.cc/https://github.com"
                "https://gh-proxy.com/https://github.com"
                "https://cors.isteed.cc/github.com"
                "https://hub.gitmirror.com/https://github.com"
                "https://download.nuaa.cf"
                "https://download.yzuu.cf"
            )
            jiashua=$((RANDOM % ${#link_url[@]}))
            url=${link_url[$jiashua]}"/bgvioletsky/DownloadApp/releases/download/"${{ env.release_tag}}"/ruanjian.zip"
            echo "è½¯ä»¶åˆé›†å‹ç¼©åŒ…ğŸ”— [ä¸‹è½½]("$url")">> release.txt
            echo "å¥¶ç‰›ğŸ”— [ä¸‹è½½]("${{env.cowtransfer}}")" >> release.txt
                        
      - name: å‘å¸ƒåˆ°release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN}}
        with:
          tag_name: ${{ env.release_tag }}
          body_path: release.txt
          files: ./path/*

      - name: åˆ é™¤è¿‡å»çš„workflow
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
          
    
      - name: åˆ é™¤è€çš„Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 10
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
