name: ä¸‹è½½è½¯ä»¶å¹¶å‘å¸ƒæ–‡ä»¶

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
   - cron: 0 17 * * 5
env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 
  UPLOAD_2: true 
  UPLOAD_3: true 
  UPLOAD_4: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: è®¾ç½®ç¯å¢ƒ Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: å®‰è£…ä¾èµ–
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: ä¸‹è½½æ–‡ä»¶
        run: |
          python ./download.py

      - name: è®¾ç½®å˜é‡
        id: compile
        run: |
          echo "bgcode=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          FILE_NAMES=($(ls ./path))
          echo "FILE_NAMES1=${FILE_NAMES[0]}" >> $GITHUB_ENV
          echo "FILE_NAMES2=${FILE_NAMES[1]}" >> $GITHUB_ENV
          echo "FILE_NAMES3=${FILE_NAMES[2]}" >> $GITHUB_ENV
          echo "FILE_NAMES4=${FILE_NAMES[3]}" >> $GITHUB_ENV
    
      - name: ä¸Šä¼ æ–‡ä»¶
        uses: actions/upload-artifact@main
        with:
          name: bgcode_${{ env.bgcode }}
          path: ./ruanjian.zip

      - name: ä¸Šä¼ æ–‡ä»¶1
        if: env.UPLOAD_1 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAMES1 }}
            path: ./path/${{ env.FILE_NAMES1 }}
      - name: ä¸Šä¼ æ–‡ä»¶2
        if: env.UPLOAD_2 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAMES2 }}
            path: ./path/${{ env.FILE_NAMES2 }}
      - name: ä¸Šä¼ æ–‡ä»¶3
        if: env.UPLOAD_3 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAMES3 }}
            path: ./path/${{ env.FILE_NAMES3 }}
      - name: ä¸Šä¼ æ–‡ä»¶4
        if: env.UPLOAD_4 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode_${{ env.FILE_NAMES4 }}
            path: ./path/${{ env.FILE_NAMES4 }}

      - name: åˆ›å»ºåˆ†æ
        id: tag
        run: |
            echo "release_tag=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV

      - name: åˆ›å»ºé“¾æ¥
        id: ss
        run: |
            link_url=(
                "https://gh.h233.eu.org/https://github.com"
                "https://gh.ddlc.top/https://github.com"
                "https://dl.ghpig.top/https://github.com"
                "https://slink.ltd/https://github.com"
                "https://git.xfj0.cn/https://github.com"
                "https://gh.con.sh/https://github.com"
                "https://ghps.cc/https://github.com"
                "https://gh-proxy.com/https://github.com"
                "https://cors.isteed.cc/github.com"
                "https://hub.gitmirror.com/https://github.com"
                "https://download.nuaa.cf"
                "https://download.yzuu.cf"
            )
            jiashua=$((RANDOM % ${#link_url[@]}))
            url=${link_url[$jiashua]}"/bgvioletsky/DownloadApp/releases/download/"${{ env.release_tag}}"/ruanjian.zip"
            echo "ğŸ”— [ä¸‹è½½]("$url")">> release.txt
            # echo "$url" >> release.txt
                        
      - name: å‘å¸ƒåˆ°release
        uses: softprops/action-gh-release@v1
        env:
          # GITHUB_TOKEN:  ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN}}
        with:
          tag_name: ${{ env.release_tag }}
          body_path: release.txt
          files: ./path/*

      - name: åˆ é™¤è¿‡å»çš„workflow
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 4
          token: ${{ secrets.MY_GIT_TOKEN }}
          # token: ${{ github.token }}
          repository:  ${{ github.repository }}
    
      - name: åˆ é™¤è€çš„Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 4
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN }}
